### ISSUE TITLE
Handle deploying to a private cluster outside of your account gracefully

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#1918]
# Bug Report

**Current behavior**

Deploying a service with a cluster property pointing to a cluster outside of your account results in this error message:

> No Node for the model Workspace with value 'workspace-slug' for slug found

<img width="591" alt="franz 2018-02-16 12-49-49" src="https://user-images.githubusercontent.com/1780597/36306427-f8655236-1317-11e8-8be6-46cfbbc36e8e.png">

**Reproduction**

* Create a private cluster
* login to your account `prisma login`
* `prisma init`, `prisma deploy`, choose your new cluster
* 'logout' locally by removing your login info from `~/.prisma/config.yml`
* `prisma deploy` -> you'll get that error message

**Expected behavior?**

Provide a better error message. Something like

* If not logged in: "Cannot not deploy to workspace 'workspace-slug'. Please login or change the cluster property in prisma.yml."
* If logged in: "Cannot deploy to workspace 'workspace-slug'. Please double check that your account is associated to this workspace or change the cluster property in prisma.yml."

**Comment by thesubway** [comment]
On prisma version 1.0.8 I was able to reproduce this error (it is fixed on 1.3.5 however).

I reproduced by:
Steps to reproduce:
(logged into prisma)

$ graphql create my-project02a --boilerplate react-fullstack-basic
And I selected prisma-us1

Then it shows up as one of my services in the prisma console.
Without changing any code (still signed in), when I do:
$ cd my-project02a/server
$ prisma deploy
It gives the above error message.

Since it now works on prisma version 1.3.5, is that a sign this is fixed?

**Comment by marktani** [comment]
I'm not sure, in your case it could be that your login is now correct and therefore you are not seeing the error anymore. @timsuchanek, do you know more? :)

**Comment by marktani** [comment]
```
ERROR: Not authorized. Please provide a proper 'Authorization' header

{
  "data": {
    "generateClusterToken": null
  },
  "errors": [
    {
      "message": "Not authorized. Please provide a proper 'Authorization' header",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "path": [
        "generateClusterToken"
      ],
      "code": 403
    }
  ],
  "status": 200
}
```

this is the error currently returned, which is more helpful.
