### ISSUE TITLE
Let user choose between `schema` in prisma.yml and `schemaPath` in .graphqlconfig if both are set

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/prisma#2056]
# Feature Request

**What feature are you missing?**

As @johannpinson pointed out [here](https://github.com/graphcool/prisma/issues/2044#issuecomment-371826263), it would be awesome if the CLI could prompt the user to choose between `schema` from `prisma.yml` and `schemaPath` from `.graphqlconfig` in the case where both are set, instead of silently choosing the `schemaPath` from `.graphqlconfig`.

**How could this feature look like in detail? Tradeoffs?**

Instead of making the decision [here](https://github.com/graphcool/prisma/blob/0acef3365f2245da0ee371be1c4768d26d83de70/cli/packages/prisma-cli-core/src/commands/deploy/index.ts#L484), it should prompt the user to select which one to choose.

**Comment by marktani** [comment]
Good idea, this is highly related to #1927.

**Comment by johannpinson** [comment]
Hey @nikolasburk 

And what about to "not give" the choice to the user to select between one of them?
Because actually, the result of using `schema` or `schemaPath` give the same `schema.graphql`file
(more or less as you can see here: https://github.com/graphcool/prisma/issues/1927#issuecomment-371566716, but it's not very important for this issue).

And because the `graphqlconfig.yml` allows more settings, it's juste about the command `graphql get-schema`.
I think a simple output in the console during the process is enough, to indicate it

Actually we just see this =>
![capture d ecran 2018-03-09 a 17 38 16](https://user-images.githubusercontent.com/2202989/37218440-b4ef2662-23c0-11e8-8ded-e601aff9deef.png)

**Comment by marktani** [comment]
`schema` was removed in `1.7.0`: https://github.com/prismagraphql/prisma/releases/tag/1.7.0
