### ISSUE TITLE
Add note about batch mutations to subscription docs

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2184]
https://www.prisma.io/docs/reference/prisma-api/mutations-ol0yuoz6go#batch-mutations has this note:

> Note that no subscription events are triggered for batch mutations!

A similar note should be added to the subscription documentation as well.

**Comment by nikolasburk** [comment]
added to the new docs

**Comment by agonbina** [comment]
@marktani @nikolasburk is there any reason why this is the case? 
We are using batch operations to implement mutations for user facing features, and since we make use of the subscriptions webhooks, this behavior limits their use to situations where you are sure that there is no batch operations on that model.
