### ISSUE TITLE
".graphqlconfig" file is not available in the provided config directory

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2335]
# Bug Report

**Current behavior**

Running `prisma playground` in a new directory created with `prisma init` opens the Playground and returns this error (in Electron app):

> ".graphqlconfig" file is not available in the provided config directory

**Reproduction**

```sh
npm install -g prisma@1.7.4
prisma init test
cd test
prisma playground
```

![image](https://user-images.githubusercontent.com/1780597/39590971-a2df6730-4f02-11e8-8798-3dc463a6072d.png)

**Expected behavior?**

My suggestion:

When `prisma playground` is run in a directory without a `.graphqlconfig.yml` file, the user can choose between
* changing directory
* automatically generating a suitable `.graphqlconfig.yml` file

**Comment by divyenduz** [comment]
@marktani, @timsuchanek : My suggestion would be to ask for the endpoint or prompt the user to create a graphql config by using `graphql init`. 

Because generating an appropriate graphql config will be "too magical" and changing directory is something away from what the user wants i.e. just exploring the API and not using graphql config at all.

While endpoint is the only information required by playground (I think) and asking for that will get the user to be able to use the playground faster.

**Comment by marktani** [comment]
This is actually a bug in Playground and should not be worked around with `prisma init`: https://github.com/prismagraphql/graphql-playground/issues/670
