### ISSUE TITLE
not able to run prisma deploy after upgrading to v1.8 with aws fargate mysql cluster

### ISSUE THREAD

**Issue by n2ctech** [prismagraphql/prisma#2384]
Steps : 
1. upgrade prisma to 1.8
2. run prisma deploy
Instead of successful deployment I got 

```
Created docker-compose.yml with a local prisma server.
Please run $ docker-compose up -d to start your local prisma.
Note: prisma local start will be deprecated soon in favor of the direct usage of docker-compose.

```
3. run prisma deploy again

```
Error : 
Creating stage dev for service pkbackfargate !
 
ERROR: GraphQL Error (Code: 405)

{
  "error": "HTTP method not allowed, supported methods: GET",
  "status": 405
}
```

**Comment by benjaminshafii** [comment]
Yeah if you're following [this](https://blog.graph.cool/how-to-deploy-a-prisma-cluster-to-aws-fargate-using-docker-cloudformation-293aa8727b89) tutorial 

it's because the `fargate.yml` file specifies only a few possible versions none of which being `1.8`

You can find `PrismaVersion` containing `AllowedValues` towards the HEAD of the file

This is what I put in mine
```yml
  PrismaVersion:
    Type: String
    Default: 1.7
    AllowedValues:
      - 1.8
      - 1.7
      - 1.6-beta
```

**Comment by marktani** [comment]
Thanks @benjaminshafii, I also assume that this was the reason for the problem.

In the meanwhile, we updated the templates: https://github.com/graphcool/prisma-templates.
Please let me know if you're still running into issues, @n2ctech! 🙂
