### ISSUE TITLE
Unable to prisma init on existing mysql db with no data

### ISSUE THREAD

**Issue by davesimtech** [prismagraphql/prisma#2516]
# Bug Report

I am currently unable to successfully run `prisma init` on a clean/new mysql database.

**Current behavior**
Prisma init fails to connect to the database:

![image](https://user-images.githubusercontent.com/39625299/40549270-e13b4296-602e-11e8-9fad-ca25db406743.png)

**Reproduction**
Setup a blank MySQL database
Run `prisma init`

**Expected behavior?**
`prisma init` completes successfully and generates config

**Investigation**

I could be wrong but when I had a dig around in EndpointDialog.ts it looks like it's creating an introspector regardless of whether your database has existing data or not:

![image](https://user-images.githubusercontent.com/39625299/40549499-866f1c56-602f-11e8-98f4-1ff64304cbf2.png)

**Comment by prolink007** [comment]
I am also experiencing this same issue. Any progress on this issue?

**Comment by jamesmbowler** [comment]
It seems only Postgres is supported .. 
[This screenshot](prisma-db-introspection) is of the files in prisma-db-introspection.

**Comment by divyenduz** [comment]
@davesimtech, @prolink007: Thanks for reporting the issue. In your case, it is not working because the docker container is not aware of `localhost` as a resolvable URL. You need to provide an accessible URI to it with a valid MySQL server. Think of it as a VM, and localhost makes the VM search internally while the MySQL server is running on the host machine. I hope this clears it for you. Thanks. 

@jamesmbowler : Indeed, introspection for MySQL is still not supported and it is tracked here: https://github.com/prismagraphql/prisma/issues/2506

But this issue is not related to that. Hence, closing it. 
Please feel free to re-open/reach out in case there are further questions. Thanks.
